version: "3.1"
services:

    gitea:
        image: gitea/gitea:1.17
        restart: unless-stopped
        networks:
          - infra
        environment:
            - USER_UID=1000
            - USER_GID=1000
        volumes:
            - ./data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.gitea.rule=Host(`git.rauhala.dev`)"
            - "traefik.http.services.gitea.loadbalancer.server.port=3000"
            - "traefik.http.routers.gitea.entrypoints=https"
            - "traefik.http.routers.gitea.tls=true"
            - "traefik.http.routers.gitea.tls.certresolver=http"
            - "traefik.http.routers.gitea.tls.domains[0].main=rauhala.dev"
            - "traefik.http.routers.gitea.tls.domains[0].sans=*.rauhala.dev"
            - "traefik.http.routers.gitea.middlewares=hideseo"
            - "traefik.http.middlewares.hideseo.headers.customresponseheaders.X-Robots-Tag=noindex"
